# Generated by Django 5.2.3 on 2025-06-12 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Antibody",
            fields=[
                ("key", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("antigen", models.CharField(max_length=255)),
                ("species", models.CharField(max_length=100)),
                ("recognizes", models.CharField(max_length=255)),
                ("vendor", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Requestor",
            fields=[
                ("key", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                ("key", models.AutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Study",
            fields=[
                ("key", models.AutoField(primary_key=True, serialize=False)),
                ("study_id", models.CharField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Tissue",
            fields=[
                ("key", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Request",
            fields=[
                ("key", models.AutoField(primary_key=True, serialize=False)),
                ("data", models.JSONField()),
                ("special_request", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "antibody",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="requests_app.antibody",
                    ),
                ),
                (
                    "requestor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="requests_app.requestor",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="requests_app.status",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="requests_app.study",
                    ),
                ),
                (
                    "tissue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="requests_app.tissue",
                    ),
                ),
            ],
        ),
    ]
