# Generated by Django 5.2.3 on 2025-06-18 22:25

import django.db.models.deletion
import requests_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="status",
            name="study",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="requests_app.study",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.ForeignKey(
                default=requests_app.models.Status.get_default_status,
                on_delete=django.db.models.deletion.CASCADE,
                to="requests_app.status",
            ),
        ),
    ]
