# Generated by Django 5.2.3 on 2025-06-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0003_remove_status_study_study_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="description",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
