# Generated by Django 5.2.3 on 2025-07-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0005_requestor_priority"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requestor",
            name="priority",
        ),
        migrations.AddField(
            model_name="request",
            name="priority",
            field=models.IntegerField(
                choices=[(1, "1 - Low"), (2, "2"), (3, "3"), (4, "4"), (5, "5 - High")],
                default=3,
            ),
        ),
    ]
