# Generated by Django 5.2.3 on 2025-07-13 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0006_remove_requestor_priority_request_priority"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignee",
            fields=[
                ("key", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("department", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="request",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="requests_app.assignee",
            ),
        ),
    ]
