# Generated by Django 5.2.3 on 2025-07-13 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0007_assignee_request_assigned_to"),
    ]

    operations = [
        migrations.CreateModel(
            name="Probe",
            fields=[
                ("key", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("sequence", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "target_gene",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("vendor", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "catalog_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="request",
            name="probe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="requests_app.probe",
            ),
        ),
    ]
