# Generated by Django 5.2.3 on 2025-07-13 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0008_probe_request_probe"),
    ]

    operations = [
        migrations.CreateModel(
            name="Priority",
            fields=[
                ("key", models.AutoField(primary_key=True, serialize=False)),
                ("value", models.IntegerField(unique=True)),
                ("label", models.CharField(max_length=50)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="probe",
            name="number_of_pairs",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="probe",
            name="platform",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="probe",
            name="target_region",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
