# Generated by Django 5.2.3 on 2025-07-13 01:38

from django.db import migrations

def populate_priorities(apps, schema_editor):
    Priority = apps.get_model('requests_app', 'Priority')
    defaults = [
        (1, '1 - Low', 'Low priority requests'),
        (2, '2', 'Low-medium priority'),
        (3, '3 - Medium', 'Medium priority requests'),
        (4, '4', 'Medium-high priority'),
        (5, '5 - High', 'High priority requests'),
    ]
    for value, label, description in defaults:
        Priority.objects.get_or_create(
            value=value,
            defaults={'label': label, 'description': description}
        )

class Migration(migrations.Migration):
    dependencies = [
        ('requests_app', '0009_priority_probe_number_of_pairs_probe_platform_and_more'),
    ]
    operations = [
        migrations.RunPython(populate_priorities, reverse_code=migrations.RunPython.noop),
    ]
