# Generated by Django 5.2.3 on 2025-07-13 01:39

import django.db.models.deletion
from django.db import migrations, models


def migrate_priority_to_fk(apps, schema_editor):
    Request = apps.get_model('requests_app', 'Request')
    Priority = apps.get_model('requests_app', 'Priority')
    for request in Request.objects.all():
        try:
            priority_obj = Priority.objects.get(value=request.priority)
            request.priority_fk = priority_obj
            request.save()
        except Priority.DoesNotExist:
            pass

class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0010_populate_priorities"),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='priority_fk',
            field=models.ForeignKey(null=True, to='requests_app.priority', on_delete=django.db.models.deletion.CASCADE),
        ),
        migrations.RunPython(migrate_priority_to_fk, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='request',
            name='priority',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='priority_fk',
            new_name='priority',
        ),
        migrations.AlterField(
            model_name='request',
            name='priority',
            field=models.ForeignKey(to='requests_app.priority', on_delete=django.db.models.deletion.CASCADE, default=3),
        ),
    ]
