# Generated by Django 5.2.3 on 2025-08-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0011_alter_request_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="antibody",
            name="archived",
            field=models.BooleanField(default=False, verbose_name="Archived"),
        ),
        migrations.AddField(
            model_name="probe",
            name="archived",
            field=models.BooleanField(default=False, verbose_name="Archived"),
        ),
        migrations.AddField(
            model_name="study",
            name="archived",
            field=models.BooleanField(default=False, verbose_name="Archived"),
        ),
    ]
