# Generated by Django 5.2.3 on 2025-08-29 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0012_antibody_archived_probe_archived_study_archived"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestChangeLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                        ],
                        max_length=20,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("special_request", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("data", models.JSONField(blank=True, null=True)),
                ("changed_fields", models.JSONField(blank=True, default=list)),
                ("change_summary", models.TextField(blank=True, null=True)),
                (
                    "antibody",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="requests_app.antibody",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="requests_app.assignee",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "priority",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="requests_app.priority",
                    ),
                ),
                (
                    "probe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="requests_app.probe",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="requests_app.request",
                    ),
                ),
                (
                    "requestor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="requests_app.requestor",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="requests_app.status",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="requests_app.study",
                    ),
                ),
                (
                    "tissue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="requests_app.tissue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Request Change Log",
                "verbose_name_plural": "Request Change Logs",
                "ordering": ["-changed_at"],
            },
        ),
    ]
