# Generated by Django 5.2.3 on 2025-08-29 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0013_requestchangelog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="antibody",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="requests_app.antibody",
            ),
        ),
    ]
