# Generated by Django 5.2.3 on 2025-09-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0014_alter_request_antibody"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestor",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email Address"
            ),
        ),
    ]
