# Generated by Django 5.2.3 on 2025-09-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0015_requestor_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("staining", "Staining Request"),
                    ("embedding", "Embedding Request"),
                    ("sectioning", "Sectioning Request"),
                ],
                default="staining",
                max_length=20,
            ),
        ),
    ]
