# Generated by Django 5.2.3 on 2025-09-14 22:17

import django.db.models.deletion
import requests_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0016_request_request_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmbeddingRequest",
            fields=[
                ("key", models.AutoField(primary_key=True, serialize=False)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("special_request", models.TextField(blank=True, null=True)),
                (
                    "number_of_animals",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Number of Animals"
                    ),
                ),
                (
                    "take_down_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Take Down Date"
                    ),
                ),
                (
                    "currently_in",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Currently In?",
                    ),
                ),
                (
                    "date_of_xylene_etoh_change",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Xylene-EtOH Change"
                    ),
                ),
                (
                    "length_of_time_in_etoh",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="Length of Time in EtOH",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="requests_app.assignee",
                    ),
                ),
                (
                    "requestor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="requests_app.requestor",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        default=requests_app.models.Status.get_default_status,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="requests_app.status",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="requests_app.study",
                    ),
                ),
                (
                    "tissues",
                    models.ManyToManyField(blank=True, to="requests_app.tissue"),
                ),
            ],
            options={
                "verbose_name": "Embedding Request",
                "verbose_name_plural": "Embedding Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SectioningRequest",
            fields=[
                ("key", models.AutoField(primary_key=True, serialize=False)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("special_request", models.TextField(blank=True, null=True)),
                (
                    "cut_surface_down",
                    models.BooleanField(default=False, verbose_name="Cut Surface Down"),
                ),
                (
                    "other",
                    models.TextField(blank=True, null=True, verbose_name="Other"),
                ),
                (
                    "sections_per_slide",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="# of Sections/Slide"
                    ),
                ),
                (
                    "slides_per_block",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="# of Slides/Block"
                    ),
                ),
                (
                    "for_what",
                    models.CharField(
                        choices=[
                            ("H&E", "H&E"),
                            ("Special stain", "Special stain"),
                            ("IHC", "IHC"),
                            ("ISH", "ISH"),
                            ("other", "Other"),
                        ],
                        default="H&E",
                        max_length=20,
                        verbose_name="For",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="requests_app.assignee",
                    ),
                ),
                (
                    "requestor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="requests_app.requestor",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        default=requests_app.models.Status.get_default_status,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="requests_app.status",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="requests_app.study",
                    ),
                ),
                (
                    "tissues",
                    models.ManyToManyField(blank=True, to="requests_app.tissue"),
                ),
            ],
            options={
                "verbose_name": "Sectioning Request",
                "verbose_name_plural": "Sectioning Requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
