# Generated by Django 5.2.3 on 2025-09-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0018_remove_embeddingrequest_tissues_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="embeddingrequest",
            name="currently_in",
            field=models.BooleanField(default=False, verbose_name="Currently In?"),
        ),
        migrations.RemoveField(
            model_name="embeddingrequest",
            name="tissues",
        ),
        migrations.AddField(
            model_name="embeddingrequest",
            name="tissues",
            field=models.ManyToManyField(blank=True, to="requests_app.tissue"),
        ),
    ]
