# Generated by Django 5.2.3 on 2025-09-15 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0019_alter_embeddingrequest_currently_in_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sectioningrequest",
            name="tissues",
        ),
        migrations.AddField(
            model_name="sectioningrequest",
            name="tissues",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="requests_app.tissue",
            ),
        ),
    ]
