# Generated by Django 5.2.3 on 2025-09-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0020_remove_sectioningrequest_tissues_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="embeddingrequest",
            name="currently_in",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")],
                default=False,
                verbose_name="Currently In?",
            ),
        ),
        migrations.AlterField(
            model_name="sectioningrequest",
            name="cut_surface_down",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")],
                default=False,
                verbose_name="Cut Surface Down",
            ),
        ),
    ]
