# Generated by Django 5.2.3 on 2025-09-17 02:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0022_remove_embeddingrequest_tissues_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="embeddingrequest",
            name="status_timestamp",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Status Set At"
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="status_timestamp",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Status Set At"
            ),
        ),
        migrations.AddField(
            model_name="sectioningrequest",
            name="status_timestamp",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Status Set At"
            ),
        ),
        migrations.AddField(
            model_name="status",
            name="status_set_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Status Set At"
            ),
        ),
    ]
