# Generated by Django 5.2.3 on 2025-09-17 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0023_embeddingrequest_status_timestamp_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StainingRequest",
            fields=[],
            options={
                "verbose_name": "Staining Request",
                "verbose_name_plural": "Staining Requests",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("requests_app.request",),
        ),
        migrations.RemoveField(
            model_name="antibody",
            name="archived",
        ),
        migrations.RemoveField(
            model_name="probe",
            name="archived",
        ),
        migrations.RemoveField(
            model_name="request",
            name="request_type",
        ),
        migrations.RemoveField(
            model_name="request",
            name="status_timestamp",
        ),
        migrations.RemoveField(
            model_name="requestor",
            name="email",
        ),
        migrations.RemoveField(
            model_name="study",
            name="archived",
        ),
        migrations.AlterField(
            model_name="request",
            name="antibody",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="requests_app.antibody"
            ),
        ),
        migrations.AlterField(
            model_name="sectioningrequest",
            name="cut_surface_down",
            field=models.BooleanField(default=False, verbose_name="Cut Surface Down"),
        ),
        migrations.CreateModel(
            name="EmbeddingRequestChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                        ],
                        max_length=20,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("changed_fields", models.JSONField(blank=True, default=list)),
                ("change_summary", models.TextField(blank=True, null=True)),
                ("data", models.JSONField(blank=True, null=True)),
                ("special_request", models.TextField(blank=True, null=True)),
                ("number_of_animals", models.IntegerField(blank=True, null=True)),
                ("take_down_date", models.DateField(blank=True, null=True)),
                ("currently_in", models.BooleanField(blank=True, null=True)),
                ("date_of_xylene_etoh_change", models.DateField(blank=True, null=True)),
                (
                    "length_of_time_in_etoh",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="requests_app.assignee",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="requests_app.embeddingrequest",
                    ),
                ),
                (
                    "requestor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="requests_app.requestor",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="requests_app.status",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="requests_app.study",
                    ),
                ),
                (
                    "tissues",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="requests_app.tissue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Embedding Request Change Log",
                "verbose_name_plural": "Embedding Request Change Logs",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="SectioningRequestChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                        ],
                        max_length=20,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("changed_fields", models.JSONField(blank=True, default=list)),
                ("change_summary", models.TextField(blank=True, null=True)),
                ("data", models.JSONField(blank=True, null=True)),
                ("special_request", models.TextField(blank=True, null=True)),
                ("cut_surface_down", models.BooleanField(blank=True, null=True)),
                ("sections_per_slide", models.IntegerField(blank=True, null=True)),
                ("slides_per_block", models.IntegerField(blank=True, null=True)),
                ("other", models.TextField(blank=True, null=True)),
                ("for_what", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="requests_app.assignee",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="requests_app.sectioningrequest",
                    ),
                ),
                (
                    "requestor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="requests_app.requestor",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="requests_app.status",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="requests_app.study",
                    ),
                ),
                (
                    "tissues",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="requests_app.tissue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sectioning Request Change Log",
                "verbose_name_plural": "Sectioning Request Change Logs",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="StainingRequestChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                        ],
                        max_length=20,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("changed_fields", models.JSONField(blank=True, default=list)),
                ("change_summary", models.TextField(blank=True, null=True)),
                ("data", models.JSONField(blank=True, null=True)),
                ("special_request", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "antibody",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="requests_app.antibody",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="requests_app.assignee",
                    ),
                ),
                (
                    "priority",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="requests_app.priority",
                    ),
                ),
                (
                    "probe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="requests_app.probe",
                    ),
                ),
                (
                    "requestor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="requests_app.requestor",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="requests_app.status",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="requests_app.study",
                    ),
                ),
                (
                    "tissue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="requests_app.tissue",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="requests_app.stainingrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staining Request Change Log",
                "verbose_name_plural": "Staining Request Change Logs",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.DeleteModel(
            name="RequestChangeLog",
        ),
    ]
