# Generated by Django 5.2.3 on 2025-09-17 20:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0024_stainingrequest_remove_antibody_archived_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="antibody",
            name="archived",
            field=models.BooleanField(default=False, verbose_name="Archived"),
        ),
        migrations.AddField(
            model_name="probe",
            name="archived",
            field=models.BooleanField(default=False, verbose_name="Archived"),
        ),
        migrations.AddField(
            model_name="request",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("staining", "Staining Request"),
                    ("embedding", "Embedding Request"),
                    ("sectioning", "Sectioning Request"),
                ],
                default="staining",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="status_timestamp",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Status Set At"
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="archived",
            field=models.BooleanField(default=False, verbose_name="Archived"),
        ),
    ]
