# Generated by Django 5.2.3 on 2025-09-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0025_antibody_archived_probe_archived_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="embeddingrequest",
            name="tissues",
        ),
        migrations.RemoveField(
            model_name="embeddingrequestchangelog",
            name="tissues",
        ),
        migrations.RemoveField(
            model_name="sectioningrequest",
            name="tissues",
        ),
        migrations.RemoveField(
            model_name="sectioningrequestchangelog",
            name="tissues",
        ),
        migrations.AddField(
            model_name="embeddingrequest",
            name="tissues",
            field=models.ManyToManyField(blank=True, to="requests_app.tissue"),
        ),
        migrations.AddField(
            model_name="embeddingrequestchangelog",
            name="tissues",
            field=models.ManyToManyField(blank=True, to="requests_app.tissue"),
        ),
        migrations.AddField(
            model_name="sectioningrequest",
            name="tissues",
            field=models.ManyToManyField(blank=True, to="requests_app.tissue"),
        ),
        migrations.AddField(
            model_name="sectioningrequestchangelog",
            name="tissues",
            field=models.ManyToManyField(blank=True, to="requests_app.tissue"),
        ),
    ]
