# Generated by Django 5.2.3 on 2025-09-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0026_remove_embeddingrequest_tissues_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="embeddingrequest",
            name="links",
            field=models.JSONField(blank=True, null=True, verbose_name="Links"),
        ),
        migrations.AddField(
            model_name="request",
            name="links",
            field=models.JSONField(blank=True, null=True, verbose_name="Links"),
        ),
        migrations.AddField(
            model_name="sectioningrequest",
            name="links",
            field=models.JSONField(blank=True, null=True, verbose_name="Links"),
        ),
    ]
