# Generated by Django 5.2.3 on 2025-09-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0027_add_links_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestor",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
