# Generated by Django 5.2.6 on 2025-09-26 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0028_requestor_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("staining", "Staining Request"),
                            ("embedding", "Embedding Request"),
                            ("sectioning", "Sectioning Request"),
                        ],
                        help_text="Type of request for these notification settings",
                        max_length=20,
                    ),
                ),
                (
                    "notify_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to send notifications for this status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.ForeignKey(
                        help_text="Status that triggers notifications",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="requests_app.status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Setting",
                "verbose_name_plural": "Notification Settings",
                "ordering": ["request_type", "status__status"],
                "unique_together": {("request_type", "status")},
            },
        ),
    ]
