# Generated by Django 5.2.6 on 2025-09-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0029_notificationsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestor",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Email address for notifications",
                max_length=254,
                null=True,
            ),
        ),
    ]
