# Generated by Django 5.2.6 on 2025-10-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0030_alter_requestor_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="embeddingrequest",
            name="currently_in",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Currently In"
            ),
        ),
        migrations.AlterField(
            model_name="embeddingrequestchangelog",
            name="currently_in",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
