# Generated by Django 5.2.3 on 2025-11-29 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0031_change_currently_in_to_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="staining_summary",
            field=models.TextField(
                blank=True, null=True, verbose_name="Staining Summary"
            ),
        ),
    ]
