# Generated by Django 5.2.3 on 2025-11-29 23:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0032_add_staining_summary"),
    ]

    operations = [
        migrations.CreateModel(
            name="AntibodyStatus",
            fields=[
                ("key", models.AutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Antibody Status",
                "verbose_name_plural": "Antibody Statuses",
                "ordering": ["status"],
            },
        ),
        migrations.AddField(
            model_name="antibody",
            name="date_created",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date Created"
            ),
        ),
        migrations.AddField(
            model_name="probe",
            name="date_created",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date Created"
            ),
        ),
        migrations.AddField(
            model_name="antibody",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="requests_app.antibodystatus",
                verbose_name="Status",
            ),
        ),
    ]
