# Generated by Django 5.2.6 on 2025-12-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0033_add_antibody_status_and_dates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="antibody",
            name="antigen",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="antibody",
            name="recognizes",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="antibody",
            name="species",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="antibody",
            name="vendor",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
