# Generated by Django 5.2.3 on 2025-12-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0035_make_probe_description_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="embeddingrequest",
            name="data",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Additional Data"
            ),
        ),
        migrations.AddField(
            model_name="sectioningrequest",
            name="data",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Additional Data"
            ),
        ),
    ]
