# Generated by Django 5.2.6 on 2026-09-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0037_add_control_tissues_to_request"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("outlook", "Microsoft Outlook / Office 365"),
                            ("gmail", "Gmail"),
                            ("custom", "Custom SMTP"),
                        ],
                        default="outlook",
                        help_text="Email provider preset",
                        max_length=20,
                    ),
                ),
                ("smtp_host", models.CharField(blank=True, max_length=255)),
                ("smtp_port", models.PositiveIntegerField(default=587)),
                ("use_tls", models.BooleanField(default=True)),
                ("use_ssl", models.BooleanField(default=False)),
                (
                    "email_address",
                    models.EmailField(
                        blank=True, help_text="SMTP login email address", max_length=254
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        help_text="Encrypted SMTP password or app password",
                        max_length=512,
                    ),
                ),
                (
                    "from_email",
                    models.EmailField(
                        blank=True,
                        help_text="Sender address shown to recipients (defaults to login email)",
                        max_length=254,
                    ),
                ),
                (
                    "admin_email",
                    models.EmailField(
                        blank=True,
                        help_text="Fallback recipient for notifications and test emails",
                        max_length=254,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Use these settings instead of environment variables",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Email Configuration",
                "verbose_name_plural": "Email Configuration",
            },
        ),
    ]
